export const OPEN_CHANGE_PASSWORD_MODAL = 'OPEN_CHANGE_PASSWORD_MODAL'
export const CLOSE_CHANGE_PASSWORD_MODAL = 'CLOSE_CHANGE_PASSWORD_MODAL'

export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL'
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL'

export const OPEN_PAYMENT_MODAL = 'OPEN_PAYMENT_MODAL'
export const CLOSE_PAYMENT_MODAL = 'CLOSE_PAYMENT_MODAL'

export const OPEN_REGISTER_MODAL = 'OPEN_REGISTER_MODAL'
export const CLOSE_REGISTER_MODAL = 'CLOSE_REGISTER_MODAL'

export const OPEN_RESET_PASSWORD_MODAL = 'OPEN_RESET_PASSWORD_MODAL'
export const CLOSE_RESET_PASSWORD_MODAL = 'CLOSE_RESET_PASSWORD_MODAL'

export const OPEN_FORGOT_PASSWORD_MODAL = 'OPEN_FORGOT_PASSWORD_MODAL'
export const CLOSE_FORGOT_PASSWORD_MODAL = 'CLOSE_FORGOT_PASSWORD_MODAL'
