export const FETCH_CURRENT_USER_COURSES_REQUEST =
  'FETCH_CURRENT_USER_COURSES_REQUEST'
export const FETCH_CURRENT_USER_COURSES_SUCCESS =
  'FETCH_CURRENT_USER_COURSES_SUCCESS'
export const FETCH_CURRENT_USER_COURSES_FAILURE =
  'FETCH_CURRENT_USER_COURSES_FAILURE'
