export const FETCH_CURRENT_USER_COURSES_REQUEST =
  'FETCH_CURRENT_USER_COURSES_REQUEST'
export const FETCH_CURRENT_USER_COURSES_SUCCESS =
  'FETCH_CURRENT_USER_COURSES_SUCCESS'
export const FETCH_CURRENT_USER_COURSES_FAILURE =
  'FETCH_CURRENT_USER_COURSES_FAILURE'

export const BUY_COURSE_REQUEST = 'REQUEST_BUY_COURSE'
export const BUY_COURSE_SUCCESS = 'BUY_COURSE_SUCCESS'
export const BUY_COURSE_FAILURE = 'BUY_COURSE_FAILURE'
