export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REQUEST = 'REQUEST'
export const REQEUST_FAILED = 'REQEUST_FAILED'
export const REGISTER = 'REGISTER'
export const REQEUST_LOGIN_FAILED = 'REQEUST_LOGIN_FAILED'

export const REQEUST_REGISTER_FAILED = 'REQEUST_REGISTER_FAILED'
