export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_DATA'
export const FETCH_NEWS_SECCESS = 'FETCH_NEWS_SECCESS'
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE'

export const FETCH_LATESTNEWS_REQUEST = 'FETCH_LATESTNEWS_DATA'
export const FETCH_LATESTNEWS_SECCESS = 'FETCH_LATESTNEWS_SECCESS'
export const FETCH_LATESTNEWS_FAILURE = 'FETCH_LATESTNEWS_FAILURE'
