export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST'
export const FETCH_NEWS_SECCESS = 'FETCH_NEWS_SECCESS'
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE'

export const FETCH_LATESTNEWS_REQUEST = 'FETCH_LATESTNEWS_REQUEST'
export const FETCH_LATESTNEWS_SECCESS = 'FETCH_LATESTNEWS_SECCESS'
export const FETCH_LATESTNEWS_FAILURE = 'FETCH_LATESTNEWS_FAILURE'

export const FETCH_CURRENTNEWS_REQUEST = 'FETCH_CURRENTNEWS_REQUEST'
export const FETCH_CURRENTNEWS_SECCESS = 'FETCH_CURRENTNEWS_SECCESS'
export const FETCH_CURRENTNEWS_FAILURE = 'FETCH_CURRENTNEWS_FAILURE'
