export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST'
export const FETCH_COURSES_SECCESS = 'FETCH_COURSES_SECCESS'
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE'

export const FETCH_LATEST_COURSES_REQUEST = 'FETCH_LATEST_COURSES_REQUEST'
export const FETCH_LATEST_COURSES_SECCESS = 'FETCH_LATEST_COURSES_SECCESS'
export const FETCH_LATEST_COURSES_FAILURE = 'FETCH_LATEST_COURSES_FAILURE'
