export const HOME_ROUTE = '/'
export const PROFILE_ROUTE = '/profile'
export const ABOUT_ROUTE = '/about'
export const CONTACT_ROUTE = '/contact'

export const NEWS_ROUTE = '/news'
export const NEWS_DETAILS_ROUTE = '/newsDetail/:id?'
export const COURSES_ROUTE = '/courses'
export const COURSE_DETAILS_ROUTE = '/course/:id?'
export const ANALYSIS_ROUTE = '/analysis'
export const SIGNAL_ROUTE = '/signal'
export const CURRENCIES_ROUTE = '/currencies'
export const INVESTMENT_ROUTE = '/investment'
export const EXCHANGE_ROUTE = '/exchange'
export const PLAY_ROUTE = '/play/:id?'
